### ISSUE TITLE
[BUG] Napari binarises synthetic images

### ISSUE THREAD

**Issue by KristinaUlicna** [alan-turing-institute/grace#108]
**Describe the bug**

I've created a dataset full of synthetic images where the entire image is set to value = 'grey' (127 for integer `dtype`, 0.5 for float `dtype`) and the squares under each node are set to the corresponding value: 'black' (0) for true negative nodes and 'white' (255 or 1.0) for true positive, object belonging nodes. I save these images as `mrc` files & check that their values are correct. 

In the napari annotator, the images are visualised as binary, i.e. only two colours in the black-and-white masks. Changing the 
``` 
with mrcfile.open(IMAGE_PATH, "r") as mrc:
    # image_data = mrc.data.astype(int)
    image_data = mrc.data 
```
^^^ Switching the `astype(int)` off or changing it to `astype(float)` doesn't help. Why is the annotator binarising the images? How can I turn this off?

![image](https://github.com/alan-turing-institute/grace/assets/48791041/5b339a84-a83d-449d-b4a7-d09e35578c64)
![Screenshot 2023-06-20 at 11 18 59](https://github.com/alan-turing-institute/grace/assets/48791041/c57d5b41-f94c-4de8-a291-3f068ff357be)

**Comment by quantumjot** [comment]
Two questions:

* What are the values in the returned `image_data` array?
```python
with mrcfile.open(IMAGE_PATH, "r") as mrc:
    # image_data = mrc.data.astype(int)
    image_data = mrc.data 
print(np.unique(image_data))
```

* Have you checked the contrast settings in napari?

**Comment by KristinaUlicna** [comment]
Let me see... dtype = float32 and the unique values are [0.  0.5 1. ] as expected for float image. For integer image, it's [0  127  255]. I checked the contrast settings, the `contrast limits` are unadjustable (cannot move along the bar).

**Comment by quantumjot** [comment]
> are unadjustable (cannot move along the bar) 

That seems like it could be the issue.

https://github.com/alan-turing-institute/grace/blob/b74c811a8f275a5179a9564f0d3c18648eae6fe4/examples/show_cbox.py#L37

Perhaps change this line to:

```python
img_layer = viewer.add_image(image_data, name=data_name, contrast_limits=(0.0, 1.0))
```
