### ISSUE TITLE
Define evaluation metrics

### ISSUE THREAD

**Issue by KristinaUlicna** [alan-turing-institute/grace#34]
Currently, it's unclear how we'll evaluate the performance of the tool,
i.e. agreement between the human-in-the-loop annotations (true) 
vs. filament predictions after the ILP step (pred). 

How about starting with the intersection over union (IoU) between true & pred nodes?
All suggestions welcome! Note: this [tutorial](https://towardsdatascience.com/evaluating-performance-of-an-object-detection-model-137a349c517b) seems helpful :-)

**Comment by quantumjot** [comment]
There are some metrics used for crYOLO here:
https://cryolo.readthedocs.io/en/stable/tutorials/tutorial_overview.html#id32

**Comment by KristinaUlicna** [comment]
Suggestions for metrics:
- crude -> accuracy, recall, precision, f1-score
- more precise -> IoU, agreement with GT

**Comment by KristinaUlicna** [comment]
Reminder: currently, there is no way of accounting for an individual object identity. This is because the annotation we provide is **semantic**, not **instance** level. Therefore, if two objects (filaments, lines, etc.) overlap, i.e. form a cross-over, there is no way of telling them apart. 

As discussed, a good way to go around this issue is to label each separate *object instance* with a different value, i.e. change the brush colour when annotating in *napari*. Potentially a new issue to raise.
